### PR TITLE
Hello AudioFX

### PR DESCRIPTION
**Pull request by micky387**
You need to rename MusicFX to AudioFX for build it.
It's the new name.

### CODE REVIEW

**Comment by varund7726** [comment]
But we don't want audioFx .we did it for a reason coz its laggy as of now

**Comment by micky387** [comment]
ok But work great on my device (samsung note edge)

**Comment by varund7726** [comment]
It doesn't lag when swiping between different equalizer modes? 
@westcrip

**Comment by micky387** [comment]
just ½  sec

**Comment by westcripp** [comment]
@micky387 UI lag makes app useless .

**Comment by micky387** [comment]
ok,as you want .

**Pull request closed without merging**
