### PR TITLE
IM A DICK HEAD ! JUST IGNORE ME . I HAVE NO LIFE 

### PR DESCRIPTION
**Pull request by droidfivex**
* you should already know why gapps (Google Apps) were separeted from ROMs.  
* **STOP FUCKING TERMS.**

### CODE REVIEW

**Comment by varund7726** [comment]
Oops does this ROM belong to you? I don't think so

**Comment by droidfivex** [comment]
I don't think so too. haha

**Comment by westcripp** [comment]
stop spamming . and do your thing

**Comment by varund7726** [comment]
You could have posted in a better way. Anyways your request is closed

**Comment by droidfivex** [comment]
lol

**Comment by ShintakuNobuhiro** [comment]
hahaha

**Comment by westcripp** [comment]
hahah

**Pull request closed without merging**
