### PR TITLE
[1/2] Make Magisk flashing opt-out

### PR DESCRIPTION
**Pull request by ashoksoni**
Change-Id: I63915def1e57cebd69c6550e80f9bc58d8b32042

### CODE REVIEW

**Comment by akhilnarang** [comment]
Gonna be pushing something similar, so closing this for now
Optional no root/los root/magisk/supersu

**Comment by ashoksoni** [comment]
Cool. Np. I closed other related pr too then.

**Comment by sayeed99** [comment]
any update on this?

**Comment by akhilnarang** [comment]
Soon™

**Comment by benbois** [comment]
good news!

**Comment by sayeed99** [comment]
our requirement is an option to select linOS-root/magisk/no-root via the
selection script that we are using to set official and stuff?? right??

**Comment by varund7726** [comment]
No .its between magisk and rootless

**Comment by benbois** [comment]
Oh, mistake for me too. What about the tool to make the selection between Magisk and lineOS SU addon? Is it already included in the RR source somewhere?

**Comment by varund7726** [comment]
Nope

**Comment by benbois** [comment]
ok thanks, I hope soon :)

**Comment by sayeed99** [comment]
https://github.com/sayeed99/android_build/commit/8a7164613da59d89b42716bf84c2839731e1d510
https://github.com/sayeed99/android_vendor_resurrection/commit/26e80d080e2ac785e8244a183eaedc794da661b5

Haven't tested it yet. But should work. Testing now anyways

**Comment by akhilnarang** [comment]
https://github.com/ResurrectionRemix/android_vendor_resurrection/commit/f1ea406c5ae760c636ca406096fb715335f63949
https://github.com/ResurrectionRemix/android_build/commit/6a510be8db3b587fcb500573097d4570291602f2

Just gotta test one final time then will merge

**Comment by sayeed99** [comment]
breaks the build, need to fix the build part. Will do it later, college
exams going on :(

**Comment by sayeed99** [comment]
https://github.com/sayeed99/android_build/commit/e74653f083b37cdc0823cdcf7735be4791599a5d
https://github.com/sayeed99/android_vendor_resurrection/commit/26e80d080e2ac785e8244a183eaedc794da661b5

works now, only issue is that the rr_su.sh script in vendor is not able to export WITH_MAGISK. 
setting export WITH_MAGISK=true in terminal/bash does the work, default is magisk. Set WITH_SU=true to use lineage root and either destruct environment or set WITH_MAGISK=false and WITH_SU=false for no root.

**Comment by akhilnarang** [comment]
@sayeed99 check my commits, working fine. Rootless/magisk. Can add in los root later if needed

**Comment by sayeed99** [comment]
looks good to me :) cheers.

**Comment by benbois** [comment]
Working fine with n7000 compilation, thanks!

**Pull request closed without merging**
