### PR TITLE
separate unofficial and official versions

### PR DESCRIPTION
**Pull request by AndropaX**
Just proposition of my concept, shorten name because it would be too long. This needs RR_RELEASE define in cm.mk for official devices. I think that type of release should be clearly showed, if you think that this isn't looks so good then we could include release type in separate section in about phone.

### CODE REVIEW

**Comment by varund7726** [comment]
Upload another patch set and change RR-M to ResurrectionRemix-M and @akhilnarang will look into it

**Comment by akhilnarang** [comment]
Can add it, but informing all maintainers about this change won't be easy, I prefer implementing this in N instead of now, then will also add this in the statistics page

**Comment by AndropaX** [comment]
Ok, this would be probably the best solution. Anyway we shouldn't wait for N so long...

**Comment by varund7726** [comment]
Yes @akhilnarang is right .asking all maintainers to do that is a long process and we SHOULD wait for N for this .

**Pull request closed without merging**
