### PR TITLE
Es File Explorer request

### PR DESCRIPTION
**Pull request by dutchman1990**
Since CM file managers function is limited, so i would like to propose Es File Manager as default file manager. This is an old version of ES, which does not contain any bloatware.

### CODE REVIEW

**Comment by varund7726** [comment]
Some user prefer CM file manager
and its also themable unlike this version of ES
Es can always be downloaded from playstore

CM file manager cant

**Comment by dutchman1990** [comment]
Ok, @varund7726 could you please take a look at this log? Is it a upstream issue or my device tree has messed up? https://drive.google.com/open?id=0BwUyo2Z0gUmKYUhpeTBUR1JMX0E

**Comment by varund7726** [comment]
What is this log for? And how is it related to this particular pull request?

**Comment by dutchman1990** [comment]
Sorry for the inconvenience, I wasn't able to contact with you directly.

**Comment by varund7726** [comment]
thats no problem. but whats the log for? just curious

**Comment by dutchman1990** [comment]
Device is cancro. Problem is camera app is causing reboot every time. even with 3rd party apps.

**Pull request closed without merging**
