### PR TITLE
vendor: Remove unnecessary launcher packages

### PR DESCRIPTION
**Pull request by Chippa-a**
* We use prebuilt Google Pixel Launcher,
   so let's use it as default.

Change-Id: I47821925a313d9dc46d27a85f6637efc14bb8c8d

### CODE REVIEW

**Comment by Chippa-a** [comment]
In my opinion here don't need the extra packages. If users want something else, they can download it.

**Comment by dragonGR** [comment]
Disagree. Trebuchet should stay. Pixel Launcher not. I don't think RR want to follow the "Your device is pixel now thanks to the launcher".

IMO, pixel launcher sucks.

**Comment by dragonGR** [comment]
With pixel launcher, you will not get the "feeling"(missing apps, plain look) if you flash pico gapps  for example.

**Comment by Chippa-a** [comment]
Actually doesn't matter which launcher. There must be something one.
I like Pixel, let's wait for another opinions =)

**Comment by ghost** [comment]
Disagree.

There must be users using Trebuchet and no reasons to remove it.

Besides, who needs Pixel launcher can install via Google Play so it won't be a problem... 

Keep Trebuchet may be a choice I think.

**Comment by ghost** [comment]
I say just stick with Trebuchet. 3/4 of the users will switch to Nova or Pixel Launcher or another 3rd party launcher anyways.

**Pull request closed without merging**
