### PR TITLE
Do you repeat the same mistake as CyanogenMod?

### PR DESCRIPTION
**Pull request by Garry050**
prebuilt: MAKE RR GREAT AGAIN

### CODE REVIEW

**Comment by westcripp** [comment]
? why

**Comment by Garry050** [comment]
DeskClock.apk
Wallpaper.apk
NexusLauncher.apk

Why including **Google Apps**?

**Comment by westcripp** [comment]
not every one flashing full gapps . like you

**Comment by Garry050** [comment]
However, Google should prohibit including GApps in unauthorized ROM.
like CyanogenMod. Have you forgotten yet?

**Comment by westcripp** [comment]
this apks not extracted from the gapps . this is play store apps . people already can insall or update them from ps

**Comment by westcripp** [comment]
like samsung did or any other OEM roms

**Comment by Garry050** [comment]
but this rom is unofficialy. not authoriezed by google.
**THIS IS NOT OEM ROM**

**Comment by westcripp** [comment]
alright why you interested this ? are you working for google ? and why its disturbing you @Garry050  ?

**Comment by Garry050** [comment]
I point out for the development team. CyanogenMod caused troubles with Google due to these.
Do you want it? I do not recommend ...

**Comment by varund7726** [comment]
Cyanogenmod was OEM in time which became CyanOS .
If we are given a warning to take it down , we will do so .
Until then stop with the unnecessary pull requests @Garry050

**Comment by Garry050** [comment]
CyanogenOS(**authoriezed**) ≠ CyanogenMod(**unauthoriezed**) stupid.
・**Stop license violation**

**Comment by varund7726** [comment]
What is violation in this lol
And @Garry050 who the hell are you ?

**Comment by varund7726** [comment]
**And stop with the stupid ass bold text you are putting .it has no effect in us .**

I can do this too you know

**Comment by varund7726** [comment]
@Garry050 are you github police? 😂😂😂

**Comment by Garry050** [comment]
Nooooooo
are u license violator? XDDDDDDD

I don't like you, but I love this ROM very much.
I don't want this rom to have trouble if possible.  that's only

**Comment by varund7726** [comment]
U don't like me then don't use our ROM :)  and yes I am a licence validator for our rom.
We decide our rules Coz its our ROM lol .and if you were a maintainer for our ROM I would've considered your request but now I never will

**Comment by Timmmmaaahh** [comment]
@Garry050 Please cease your moral entrepreneurship immediately. Hundreds of custom ROM compilations are equipped with aforementioned software and a selection of other proprietary elements. Keep in mind that none of these distributions implement Google Play services, the absolute core of Google Apps, by default. Not to mention that the cease and desist by Google was preceded by a major dispute between both companies. As Google prevailed, it is safe to assume they have a certain tolerance towards these practices, even if it violates their terms. As @varund7726 mentions, if the Resurrection Remix team receives a similar cease and desist claim by Google, they will of course comply, this does not need user intervention. However, history teaches us that this has only occurred once and the situation today is quite different. Currently, your beloved ROM only has only one endangerment, your persistent attention hogging that consumes valuable coding time from highly respected and most valuable developers. Consider this my personal cease and desist in your direction, Garry.

**Comment by akhilnarang** [comment]
@Garry050 afaik CM had an issue because they shipped full GApps packages, including Play Services and stuff. Just these apps, which can be installed from play store anyway, shouldn't be an issue. As others have said, if google has any issue and they contact us, we'll remove these immediately

**Comment by varund7726** [comment]
Well said @Timmmmaaahh

**Comment by Garry050** [comment]
okay, I will silent about this
sorry teams

**Pull request closed without merging**
