### PR TITLE
Remove double entries

### PR DESCRIPTION
**Pull request by Jaiglissechef-i9100**

### CODE REVIEW

**Comment by akhilnarang** [comment]
Where else is it?

**Comment by Jaiglissechef-i9100** [comment]
Just a double entries

**Comment by Jaiglissechef-i9100** [comment]
line 96/98 and line 100/102

**Comment by akhilnarang** [comment]
96-98 is for boot jars
100-102 is for packages

**Comment by Jaiglissechef-i9100** [comment]
oh my bad, sorry.

**Pull request closed without merging**
